name: CI
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Sdkgen.Client
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/Sdkgen.Client.Tests
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 8081:80
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        run: dotnet test